#ifndef _GALE_SYNTH_UI_WINDOW_MAIN_CONSTANTS_H_
#define _GALE_SYNTH_UI_WINDOW_MAIN_CONSTANTS_H_

#define PORT_WIDTH 10
#define PORT_HEIGHT 10
#define NAME_MARGIN_HORIZONTAL 10
#define PAD_VERTICAL 25
#define PAD_PORTS 10

#endif